const wordLists = {
    "Day1": [
        ["a", "하나의"],
        ["about", "~에 관하여"],
        ["across", "~을 가로질러"],
        ["act", "행동"],
        ["address", "주소"],
        ["afraid", "두려워하여"],
        ["after", "~후에"],
        ["afternoon", "오후"],
        ["again", "다시"],
        ["age", "나이"],
    ],
    "Day2": [
        ["ago", "~전에"],
        ["air", "공기"],
        ["airport", "공항"],
        ["album", "사진첩"],
        ["all", "모두"],
        ["along", "~을 따라서"],
        ["always", "항상"],
        ["among", "~사이에서"],
        ["and", "그리고"],
        ["angry", "성난"],
    ],
    "Day3": [
        ["animal", "동물"],
        ["answer", "대답"],
        ["any", "어떤"],
        ["apartment", "아파트"],
        ["apple", "사과"],
        ["arm", "팔"],
        ["around", "~주위에"],
        ["arrive", "도착하다"],
        ["as", "~같은/~로서"],
        ["ask", "묻다"],
    ],
    "Day4": [
        ["at", "~에"],
        ["aunt", "이모,고모"],
        ["autumn", "가을"],
        ["away", "떨어져"],
        ["baby", "아기"],
        ["back", "뒤에"],
        ["bad", "나쁜"],
        ["bag", "가방"],
        ["ball", "공"],
        ["balloon", "풍선"],
    ],
    "Day5": [
        ["banana", "바나나"],
        ["band", "끈/악단"],
        ["bank", "은행"],
        ["base", "기초"],
        ["basket", "바구니"],
        ["bath", "목욕"],
        ["be", "~이다"],
        ["beach", "해변"],
        ["bear", "곰"],
        ["beautiful", "아름다움"],
    ],
    "Day6": [
        ["because", "~때문에"],
        ["become", "~이되다"],
        ["bed", "침대"],
        ["before", "~전에"],
        ["begin", "시작하다"],
        ["behind", "~뒤에"],
        ["bell", "종"],
        ["below", "~아래"],
        ["bench", "긴의자"],
        ["beside", "~곁에"],
    ],
    "Day7": [
        ["between", "~사이에"],
        ["bicycle", "자전거"],
        ["big", "큰"],
        ["bird", "새"],
        ["birthday", "생일"],
        ["black", "검정색"],
        ["blow", "불다"],
        ["blue", "푸른"],
        ["board", "판자"],
        ["boat", "배"],
    ],
    "Day8": [
        ["body", "몸"],
        ["book", "책"],
        ["bottle", "병"],
        ["bowl", "사발"],
        ["box", "상자"],
        ["boy", "소년"],
        ["bread", "빵"],
        ["break", "깨뜨리다"],
        ["breakfast", "아침"],
        ["bridge", "다리"],
    ],
    "Day9": [
        ["bright", "밝은"],
        ["bring", "가져오다"],
        ["brother", "형제"],
        ["brown", "갈색"],
        ["brush", "솔"],
        ["build", "건설하다"],
        ["burn", "불타다"],
        ["bus", "버스"],
        ["busy", "바쁜"],
        ["but", "그러나"],
    ],
    "Day10": [
        ["butter", "버터"],
        ["button", "단추"],
        ["buy", "사다"],
        ["by", "~옆에"],
        ["bye", "안녕"],
        ["calendar", "달력"],
        ["cake", "케이크"],
        ["call", "부르다"],
        ["camera", "사진기"],
        ["camp", "야영지"],
    ],
    "Day11": [
        ["can", "할수있다"],
        ["candle", "양초"],
        ["candy", "사탕"],
        ["cap", "모자"],
        ["capital", "수도/대문자"],
        ["captain", "우두머리"],
        ["car", "자동차"],
        ["card", "카드"],
        ["care", "걱정/돌보다"],
        ["carry", "나르다"],
    ],
    "Day12": [
        ["case", "경우"],
        ["cassette", "카셋트"],
        ["cat", "고양이"],
        ["catch", "붙잡다"],
        ["ceiling", "천장"],
        ["center", "중앙"],
        ["chair", "의자"],
        ["chalk", "분필"],
        ["chance", "기회"],
        ["change", "바꾸다"],
    ],
    "Day13": [
        ["cheap", "값싼"],
        ["cheese", "치즈"],
        ["chicken", "닭"],
        ["child", "어린이"],
        ["chopstick", "젓가락"],
        ["church", "교회"],
        ["circle", "원"],
        ["city", "도시"],
        ["class", "학급"],
        ["classmate", "동급생"],
    ],
    "Day14": [
        ["clean", "깨끗한"],
        ["climb", "오르다"],
        ["clock", "시계"],
        ["close", "닫다"],
        ["clothes", "옷"],
        ["cloud", "구름"],
        ["club", "클럽"],
        ["coat", "코트"],
        ["coffee", "커피"],
        ["coin", "동전"],
    ],
    "Day15": [
        ["cold", "추운"],
        ["color", "색깔"],
        ["come", "오다"],
        ["computer", "컴퓨터"],
        ["cook", "요리하다"],
        ["cool", "시원한"],
        ["copy", "사본, 베끼다"],
        ["corner", "모퉁이"],
        ["count", "세다"],
        ["country", "지역"],
    ],
    "Day16": [
        ["course", "과정"],
        ["cousin", "사촌"],
        ["cover", "덮다"],
        ["cow", "암소"],
        ["crayon", "크레용"],
        ["cream", "크림"],
        ["cross", "가로지르다"],
        ["cry", "울다"],
        ["cup", "컵"],
        ["curtain", "커튼"],
    ],
    "Day17": [
        ["cut", "자르다"],
        ["dad", "아빠"],
        ["dance", "춤추다"],
        ["danger", "위험한"],
        ["dark", "어두운"],
        ["date", "날짜"],
        ["daughter", "딸"],
        ["day", "낮, 하루"],
        ["dead", "죽은"],
        ["deep", "깊은"],
    ],
    "Day18": [
        ["dear", "존경하는"],
        ["desk", "책상"],
        ["dial", "다이얼"],
        ["diary", "일기"],
        ["dictionary", "사전"],
        ["die", "죽다"],
        ["dinner", "저녁"],
        ["dirty", "더러운"],
        ["dish", "큰접시"],
        ["do", "하다"],
    ],
    "Day19": [
        ["doctor", "의사"],
        ["dog", "개"],
        ["doll", "인형"],
        ["dollar", "달러"],
        ["dolphin", "돌고래"],
        ["door", "문"],
        ["down", "아래에"],
        ["draw", "그리다"],
        ["dream", "꿈"],
        ["dress", "드레스"],
    ],
    "Day20": [
        ["drink", "마시다"],
        ["drive", "운전하다"],
        ["drop", "떨어지다, 방울"],
        ["drum", "북"],
        ["dry", "마른"],
        ["duck", "오리"],
        ["ear", "귀"],
        ["early", "일찍"],
        ["earth", "지구"],
        ["east", "동쪽"],
    ],
    "Day21": [
        ["easy", "쉬운"],
        ["eat", "먹다"],
        ["egg", "계란"],
        ["empty", "텅빈"],
        ["end", "끝"],
        ["engine", "엔진"],
        ["enjoy", "즐기다"],
        ["enough", "충분한"],
        ["eraser", "지우개"],
        ["evening", "저녁"],
    ],
    "Day22": [
        ["every", "모든, 모두의"],
        ["example", "예, 보기"],
        ["excellent", "뛰어난"],
        ["excite", "흥분시키다"],
        ["excuse", "용서하다"],
        ["exercise", "연습"],
        ["eye", "눈"],
        ["face", "얼굴"],
        ["fact", "사실"],
        ["fair", "공정한"],
    ],
    "Day23": [
        ["fall", "가을, 떨어지다"],
        ["family", "가족"],
        ["far", "멀리 떨어진"],
        ["farm", "농장"],
        ["fast", "빠른"],
        ["fat", "살찐"],
        ["famous", "유명한"],
        ["father", "아버지"],
        ["feel", "느끼다"],
        ["few", "다소 양이 적은"],
    ],
    "Day24": [
        ["field", "들판, 경기장"],
        ["fight", "싸움"],
        ["fill", "채우다"],
        ["film", "필름"],
        ["find", "찾다"],
        ["fine", "좋은, 맑은"],
        ["finger", "손가락"],
        ["finish", "끝내다"],
        ["fire", "불"],
        ["fish", "고기, 낚시하다"],
    ],
    "Day25": [
        ["fix", "고정시키다"],
        ["flag", "깃발"],
        ["floor", "마루"],
        ["flower", "꽃"],
        ["fly", "날다"],
        ["follow", "뒤를 따르다"],
        ["food", "음식"],
        ["fool", "바보"],
        ["foot", "발"],
        ["for", "~을 위하여, ~동안"],
    ],
    "Day26": [
        ["forget", "잊다"],
        ["fork", "포크"],
        ["free", "자유로운"],
        ["fresh", "신선한"],
        ["friend", "친구"],
        ["from", "~로부터"],
        ["front", "앞/정면"],
        ["fruit", "과일"],
        ["full", "가득찬"],
        ["fun", "즐거움"],
    ],
    "Day27": [
        ["game", "놀이"],
        ["garden", "정원"],
        ["gas", "가스, 휘발유"],
        ["gate", "문"],
        ["gentle", "온화한"],
        ["get", "얻다"],
        ["girl", "소녀"],
        ["give", "주다"],
        ["glad", "기쁜"],
        ["glass", "유리, 컵"],
    ],
    "Day28": [
        ["glove", "장갑"],
        ["go", "가다"],
        ["god(GOD)", "신, 하나님"],
        ["gold", "금"],
        ["good", "좋은"],
        ["grandmother", "할머니"],
        ["grape", "포도"],
        ["grass", "풀, 잔디"],
        ["gray", "회색"],
        ["great", "큰"],
    ],
    "Day29": [
        ["green", "녹색"],
        ["ground", "땅, 기초"],
        ["group", "단체"],
        ["grow", "성장하다"],
        ["guitar", "기타"],
        ["hair", "머리카락"],
        ["half", "절반"],
        ["hall", "회관, 넓은 방"],
        ["hamburger", "햄버거"],
        ["hand", "손"],
    ],
    "Day30": [
        ["handle", "손잡이"],
        ["happen", "발생하다"],
        ["happy", "행복한"],
        ["hard", "단단한, 열심히"],
        ["hat", "모자"],
        ["hate", "미워하다"],
        ["have", "가지고 있다"],
        ["he", "그, 남자"],
        ["head", "머리"],
        ["hear", "듣다"],
    ],
    "Day31": [
        ["heart", "마음"],
        ["heavy", "무거운"],
        ["hello", "여보세요"],
        ["help", "돕다"],
        ["hen", "암닭"],
        ["here", "여기에서"],
        ["hi", "안녕하세요"],
        ["hide", "숨기다"],
        ["high", "높은"],
        ["hiking", "하이킹, 도보여행"]
    ],

    "Day32": [
        ["hill", "언덕"],
        ["hit", "때리다"],
        ["hold", "잡다"],
        ["hole", "구멍"],
        ["holiday", "휴일"],
        ["home", "집"],
        ["hope", "희망"],
        ["hose", "호스"],
        ["horse", "말"],
        ["hospital", "병원"]
    ],

    "Day33": [
        ["hot", "뜨거운"],
        ["hotel", "호텔"],
        ["hour", "시간"],
        ["house", "집"],
        ["how", "어떻게"],
        ["hundred", "100"],
        ["hungry", "배고픈"],
        ["hurry", "서두르다"],
        ["hurt", "다치게하다"],
        ["I", "나"]
    ],

    "Day34": [
        ["ice", "얼음"],
        ["idea", "생각"],
        ["if", "만약"],
        ["ill", "병든"],
        ["in", "~속"],
        ["ink", "잉크"],
        ["interest", "흥미"],
        ["into", "~속으로"],
        ["introduce", "소개하다"],
        ["island", "섬"]
    ],

    "Day35": [
        ["it", "그것"],
        ["job", "직업"],
        ["join", "가입하다"],
        ["juice", "주스"],
        ["jump", "뛰어오르다"],
        ["jungle", "밀림지대"],
        ["just", "오직, 겨우"],
        ["keep", "지키다, 유지하다"],
        ["key", "열쇠"],
        ["kick", "차다"]
    ],

    "Day36": [
        ["kid", "아이"],
        ["kill", "죽이다"],
        ["kind", "친절한, 종류"],
        ["king", "왕"],
        ["kitchen", "부엌"],
        ["knee", "무릎"],
        ["knife", "칼"],
        ["knock", "두드리다"],
        ["know", "알다"],
        ["lady", "숙녀"]
    ],

    "Day37": [
        ["lake", "호수"],
        ["lamp", "등불"],
        ["land", "땅"],
        ["large", "큰, 넓은"],
        ["last", "마지막, 최근"],
        ["late", "늦은"],
        ["laugh", "웃다"],
        ["lead", "인도하다"],
        ["leaf", "잎"],
        ["learn", "배우다"]
    ],

    "Day38": [
        ["leave", "떠나다"],
        ["left", "왼쪽"],
        ["leg", "다리"],
        ["lesson", "학과"],
        ["let", "허락하다"],
        ["letter", "편지"],
        ["library", "도서관"],
        ["lie", "눕다, 거짓말하다"],
        ["light", "빛"],
        ["like", "좋아하다"]
    ],

    "Day39": [
        ["line", "선, 줄"],
        ["lion", "사자"],
        ["lip", "입술"],
        ["list", "목록"],
        ["listen", "듣다"],
        ["little", "작은"],
        ["live", "살다, 생생한"],
        ["long", "긴"],
        ["look", "바라보다"],
        ["lose", "잃다"]
    ],

    "Day40": [
        ["lot", "많음"],
        ["loud", "소리가 큰"],
        ["love", "사랑하다"],
        ["low", "낮은"],
        ["luck", "행운"],
        ["lunch", "점심식사"],
        ["ma'am", "아주머니"],
        ["mad", "미친"],
        ["mail", "우편"],
        ["make", "만들다"]
    ],
    "Day41": [
        ["man", "사람, 남자"],
        ["many", "많은"],
        ["map", "지도"],
        ["march", "행진, 3월"],
        ["market", "상점"],
        ["marry", "결혼하다"],
        ["matter", "문제"],
        ["may", "~해도좋다, 5월"],
        ["meat", "고기"],
        ["medal", "메달"]
    ],
    "Day42": [
        ["meet", "만나다"],
        ["melon", "멜론"],
        ["meter", "미터"],
        ["middle", "한가운데"],
        ["milk", "우유"],
        ["million", "100만"],
        ["minute", "분, 순간"],
        ["mirror", "거울"],
        ["Miss", "~양, 호칭"],
        ["model", "모형"]
    ],
    "Day43": [
        ["mom(my)", "엄마"],
        ["money", "돈"],
        ["monkey", "원숭이"],
        ["month", "달, 개월"],
        ["moon", "달"],
        ["morning", "아침"],
        ["mother", "어머니"],
        ["mountain", "산"],
        ["mouth", "입"],
        ["move", "움직이다"]
    ],
    "Day44": [
        ["movie", "영화"],
        ["Mr.", "~씨"],
        ["Mrs.", "~여사"],
        ["much", "많은"],
        ["music", "음악"],
        ["must", "~해야한다"],
        ["name", "이름"],
        ["narrow", "좁은"],
        ["near", "가까운"],
        ["neck", "목"]
    ],
    "Day45": [
        ["need", "필요하다"],
        ["never", "결코~않다"],
        ["new", "새로운"],
        ["news", "뉴스"],
        ["next", "다음의"],
        ["nice", "좋은"],
        ["night", "밤"],
        ["no", "아니다, 없다"],
        ["noise", "소음"],
        ["north", "북쪽"]
    ],
    "Day46": [
        ["nose", "코"],
        ["not", "아니다"],
        ["note", "공책"],
        ["now", "지금"],
        ["number", "숫자"],
        ["nurse", "간호원"],
        ["o'clock", "~시 정각"],
        ["of", "~의"],
        ["off", "떨어진, 끄다"],
        ["office", "사무실"]
    ],
    "Day47": [
        ["often", "흔히/종종"],
        ["oh", "오!"],
        ["oil", "기름"],
        ["okay(ok)", "좋아"],
        ["old", "늙은"],
        ["on", "~위에"],
        ["once", "한번"],
        ["only", "오직"],
        ["open", "열린"],
        ["or", "또는"]
    ],
    "Day48": [
        ["orange", "오렌지"],
        ["other", "그밖의"],
        ["out", "밖에"],
        ["over", "~위쪽에"],
        ["page", "쪽"],
        ["paint", "칠하다"],
        ["pair", "짝"],
        ["pants", "바지"],
        ["paper", "종이"],
        ["pardon", "용서하다"]
    ],
    "Day49": [
        ["parent", "부모"],
        ["park", "공원"],
        ["party", "파티"],
        ["pass", "통과하다"],
        ["pay", "지불하다"],
        ["peace", "평화"],
        ["pear", "배"],
        ["pen", "펜, 만년필"],
        ["pencil", "연필"],
        ["people", "사람"]
    ],
    "Day50": [
        ["piano", "피아노"],
        ["pick", "따다, 골라내다"],
        ["picnic", "소풍"],
        ["picture", "그림"],
        ["piece", "조각"],
        ["pig", "돼지"],
        ["pilot", "조종사"],
        ["pin", "핀"],
        ["pine", "소나무"],
        ["pink", "분홍"]
    ],
    "Day51": [
        ["pipe", "파이프, 판"],
        ["place", "장소"],
        ["plan", "계획"],
        ["plane", "비행기"],
        ["plant", "식물"],
        ["play", "놀다"],
        ["please", "기쁘게하다, 제발"],
        ["pocket", "주머니"],
        ["point", "점수, 요점"],
        ["police", "경찰"]
    ],
    "Day52": [
        ["pool", "웅덩이"],
        ["poor", "가난한"],
        ["post", "기둥, 우편"],
        ["poster", "포스터"],
        ["potato", "감자"],
        ["practice", "연습, 습관"],
        ["present", "현재, 선물"],
        ["pretty", "예쁜"],
        ["print", "인쇄하다"],
        ["problem", "문제"]
    ],
    "Day53": [
        ["pull", "끌다"],
        ["push", "밀다"],
        ["put", "놓다"],
        ["queen", "여왕"],
        ["question", "질문"],
        ["quick", "빠른"],
        ["quiet", "조용한"],
        ["radio", "라디오"],
        ["rain", "비"],
        ["rainbow", "무지개"]
    ],
    "Day54": [
        ["read", "읽다"],
        ["ready", "준비가 된"],
        ["real", "실제하는"],
        ["record", "기록하다"],
        ["red", "빨강"],
        ["remember", "기억하다"],
        ["repeat", "반복하다"],
        ["rest", "휴식"],
        ["restaurant", "식당"],
        ["return", "되돌아가다"]
    ],
    "Day55": [
        ["ribbon", "리본"],
        ["rice", "쌀"],
        ["rich", "부유한"],
        ["ride", "타다"],
        ["right", "오른쪽, 옳은"],
        ["ring", "반지, 고리"],
        ["river", "강"],
        ["road", "길"],
        ["robot", "로보트"],
        ["rock", "바위"]
    ],
    "Day56": [
        ["rocket", "로켓"],
        ["roll", "구르다"],
        ["roof", "지붕"],
        ["room", "방"],
        ["rose", "장미"],
        ["round", "둥근"],
        ["ruler", "자"],
        ["run", "달리다"],
        ["sad", "슬픈"],
        ["safe", "안전한"]
    ],
    "Day57": [
        ["salt", "소금"],
        ["salad", "샐러드"],
        ["same", "같은"],
        ["sand", "모래"],
        ["say", "말하다"],
        ["school", "학교"],
        ["score", "점수"],
        ["sea", "바다"],
        ["season", "계절"],
        ["seat", "의자, 좌석"]
    ],
    "Day58": [
        ["see", "보다"],
        ["sell", "팔다"],
        ["send", "보내다"],
        ["service", "봉사하다"],
        ["set", "놓다"],
        ["shall", "~일것이다"],
        ["shape", "모양"],
        ["she", "그녀"],
        ["sheep", "양"],
        ["sheet", "시트, 한장"]
    ],
    "Day59": [
        ["ship", "배"],
        ["shirt", "셔츠"],
        ["shoe", "구두"],
        ["shoot", "쏘다"],
        ["shop", "가게"],
        ["short", "짧은"],
        ["shoulder", "어깨"],
        ["shout", "외치다"],
        ["show", "보이다"],
        ["shower", "소나기, 샤워"]
    ],
    "Day60": [
        ["shut", "닫다"],
        ["sick", "아픈"],
        ["side", "옆, 측면"],
        ["sign", "기호, 신호"],
        ["silver", "은"],
        ["sing", "노래하다"],
        ["sir", "~님, ~씨"],
        ["sister", "자매"],
        ["sit", "앉다"],
        ["size", "크기"]
    ],
    "Day61": [
        ["skate", "스케이트"],
        ["skirt", "치마"],
        ["sky", "하늘"],
        ["sleep", "잠자다"],
        ["slide", "미끄러지다"],
        ["slow", "느린"],
        ["small", "작은"],
        ["smell", "냄새나다"],
        ["smile", "웃다"],
        ["smoke", "연기"]
    ],
    "Day62": [
        ["snow", "눈"],
        ["so", "그와같은"],
        ["soap", "비누"],
        ["soccer", "축구"],
        ["sock", "양말"],
        ["soft", "부드러운"],
        ["some", "약간의"],
        ["son", "아들"],
        ["song", "노래"],
        ["soon", "곧"]
    ],
    "Day63": [
        ["sorry", "슬픈, 유감의"],
        ["sound", "소리"],
        ["soup", "스프"],
        ["south", "남쪽"],
        ["space", "공간, 우주"],
        ["speak", "이야기하다"],
        ["speed", "속력"],
        ["spell", "철자"],
        ["spend", "낭비하다"],
        ["spoon", "숟가락"]
    ],
    "Day64": [
        ["sport", "운동경기"],
        ["spring", "봄, 용수철"],
        ["square", "정사각형"],
        ["stairs", "계단, 사닥다리"],
        ["stamp", "우편"],
        ["stand", "서다"],
        ["star", "별"],
        ["start", "출발하다"],
        ["station", "정거장"],
        ["stay", "머물다"]
    ],
    "Day65": [
        ["steam", "증기"],
        ["step", "한걸음"],
        ["stick", "막대기"],
        ["stone", "돌멩이"],
        ["stop", "멈추다"],
        ["store", "가게"],
        ["storm", "폭풍우"],
        ["story", "이야기"],
        ["stove", "스토브, 난로"],
        ["straight", "곧은"]
    ],
    "Day66": [
        ["strange", "이상한, 낯선"],
        ["strawberry", "딸기"],
        ["street", "거리"],
        ["strike", "치다"],
        ["strong", "강한"],
        ["student", "학생"],
        ["study", "공부하다"],
        ["stupid", "어리석은"],
        ["subway", "지하철"],
        ["sugar", "설탕"]
    ],
    "Day67": [
        ["summer", "여름"],
        ["sun", "태양"],
        ["supermarket", "슈퍼마켓"],
        ["supper", "저녁식사"],
        ["sure", "확실한"],
        ["surprise", "놀라운"],
        ["sweater", "스웨터"],
        ["sweet", "달콤한"],
        ["swim", "수영"],
        ["swing", "흔들리다"]
    ],
    "Day68": [
        ["switch", "스위치"],
        ["table", "식탁, 탁자"],
        ["take", "잡다, 가져가다"],
        ["talk", "말하다"],
        ["tall", "키가 큰"],
        ["taste", "맛"],
        ["taxi", "택시"],
        ["tea", "차"],
        ["team", "팀"],
        ["telephone", "전화"]
    ],
    "Day69": [
        ["television", "텔레비전"],
        ["ten", "10"],
        ["thank", "감사하다"],
        ["that", "그것"],
        ["the", "그"],
        ["their", "그들의"],
        ["them", "그들을"],
        ["then", "그때"],
        ["there", "그곳"],
        ["they", "그들"]
    ],
    "Day70": [
        ["thick", "두꺼운"],
        ["thin", "얇은"],
        ["think", "생각하다"],
        ["this", "이것"],
        ["those", "그것들"],
        ["thousand", "천"],
        ["time", "시간"],
        ["tiny", "작은"],
        ["tired", "피곤한"],
        ["to", "~로"]
    ],
    "Day71": [
        ["today", "오늘"],
        ["together", "함께"],
        ["tomorrow", "내일"],
        ["tone", "음성, 어조"],
        ["too", "너무"],
        ["tool", "도구"],
        ["top", "상단"],
        ["together", "함께"],
        ["touch", "닿다"],
        ["town", "도시"]
    ],
    "Day72": [
        ["toy", "장난감"],
        ["track", "경주로"],
        ["train", "기차"],
        ["tree", "나무"],
        ["trip", "여행"],
        ["trolley", "트롤리"],
        ["truck", "트럭"],
        ["true", "진실된"],
        ["try", "시도하다"],
        ["turn", "돌다"]
    ],
    "Day73": [
        ["twelve", "12"],
        ["twenty", "20"],
        ["twice", "두번"],
        ["under", "아래"],
        ["understand", "이해하다"],
        ["unit", "단위"],
        ["up", "위로"],
        ["use", "사용하다"],
        ["useful", "유용한"],
        ["usually", "보통"]
    ],
    "Day74": [
        ["vacation", "휴가"],
        ["valley", "계곡"],
        ["vase", "꽃병"],
        ["vegetable", "채소"],
        ["very", "매우"],
        ["view", "전망"],
        ["village", "마을"],
        ["visit", "방문하다"],
        ["voice", "목소리"],
        ["vote", "투표하다"]
    ],
    "Day75": [
        ["wait", "기다리다"],
        ["walk", "걷다"],
        ["wall", "벽"],
        ["want", "원하다"],
        ["war", "전쟁"],
        ["warm", "따뜻한"],
        ["wash", "씻다"],
        ["watch", "보다, 시계"],
        ["water", "물"],
        ["way", "길"]
    ],
    "Day76": [
        ["we", "우리는"],
        ["wear", "입다"],
        ["weather", "날씨"],
        ["week", "주"],
        ["weight", "무게"],
        ["welcome", "환영하다"],
        ["well", "잘"],
        ["west", "서쪽"],
        ["what", "무엇"],
        ["when", "언제"]
    ],
    "Day77": [
        ["where", "어디"],
        ["which", "어떤"],
        ["while", "동안"],
        ["who", "누구"],
        ["why", "왜"],
        ["wide", "넓은"],
        ["wife", "아내"],
        ["wild", "야생의"],
        ["win", "이기다"],
        ["winter", "겨울"]
    ],
    "Day78": [
        ["wish", "바라다"],
        ["with", "~와 함께"],
        ["woman", "여자"],
        ["wonder", "궁금하다"],
        ["wood", "나무"],
        ["word", "단어"],
        ["work", "일하다"],
        ["world", "세상"],
        ["worry", "걱정하다"],
        ["worse", "더 나쁜"]
    ],
    "Day79": [
        ["write", "쓰다"],
        ["wrong", "잘못된"],
        ["year", "연도"],
        ["yellow", "노란"],
        ["yes", "네"],
        ["yesterday", "어제"],
        ["you", "너"],
        ["young", "젊은"],
        ["your", "당신의"],
        ["youth", "청춘"]
    ],
    "Day80": [
        ["zebra", "얼룩말"],
        ["zero", "0"],
        ["zinc", "아연"],
        ["zone", "구역"],
        ["zoom", "확대하다"]
    ],
}