const wordLists = {
    "Day1": [
    ["a", "하나의"],
    ["about", "~에 관하여"],
    ["across", "~을 가로질러"],
    ["act", "행동"],
    ["address", "주소"],
    ["afraid", "두려워하여"],
    ["after", "~후에"],
    ["afternoon", "오후"],
    ["again", "다시"],
    ["age", "나이"],
  ],
  "Day2": [
    ["ago", "~전에"],
    ["air", "공기"],
    ["airport", "공항"],
    ["album", "사진첩"],
    ["all", "모두"],
    ["along", "~을 따라서"],
    ["always", "항상"],
    ["among", "~사이에서"],
    ["and", "그리고"],
    ["angry", "성난"],
  ],
  "Day3": [
    ["animal", "동물"],
    ["answer", "대답"],
    ["any", "어떤"],
    ["apartment", "아파트"],
    ["apple", "사과"],
    ["arm", "팔"],
    ["around", "~주위에"],
    ["arrive", "도착하다"],
    ["as", "~같은/~로서"],
    ["ask", "묻다"],
  ],
  "Day4": [
    ["at", "~에"],
    ["aunt", "이모,고모"],
    ["autumn", "가을"],
    ["away", "떨어져"],
    ["baby", "아기"],
    ["back", "뒤에"],
    ["bad", "나쁜"],
    ["bag", "가방"],
    ["ball", "공"],
    ["balloon", "풍선"],
  ],
  "Day5": [
    ["banana", "바나나"],
    ["band", "끈/악단"],
    ["bank", "은행"],
    ["base", "기초"],
    ["basket", "바구니"],
    ["bath", "목욕"],
    ["be", "~이다"],
    ["beach", "해변"],
    ["bear", "곰"],
    ["beautiful", "아름다움"],
  ],
  "Day6": [
    ["because", "~때문에"],
    ["become", "~이되다"],
    ["bed", "침대"],
    ["before", "~전에"],
    ["begin", "시작하다"],
    ["behind", "~뒤에"],
    ["bell", "종"],
    ["below", "~아래"],
    ["bench", "긴의자"],
    ["beside", "~곁에"],
  ],
  "Day7": [
    ["between", "~사이에"],
    ["bicycle", "자전거"],
    ["big", "큰"],
    ["bird", "새"],
    ["birthday", "생일"],
    ["black", "검정색"],
    ["blow", "불다"],
    ["blue", "푸른"],
    ["board", "판자"],
    ["boat", "배"],
  ],
  "Day8": [
    ["body", "몸"],
    ["book", "책"],
    ["bottle", "병"],
    ["bowl", "사발"],
    ["box", "상자"],
    ["boy", "소년"],
    ["bread", "빵"],
    ["break", "깨뜨리다"],
    ["breakfast", "아침"],
    ["bridge", "다리"],
  ],
  "Day9": [
    ["bright", "밝은"],
    ["bring", "가져오다"],
    ["brother", "형제"],
    ["brown", "갈색"],
    ["brush", "솔"],
    ["build", "건설하다"],
    ["burn", "불타다"],
    ["bus", "버스"],
    ["busy", "바쁜"],
    ["but", "그러나"],
  ],
  "Day10": [
    ["butter", "버터"],
    ["button", "단추"],
    ["buy", "사다"],
    ["by", "~옆에"],
    ["bye", "안녕"],
    ["calendar", "달력"],
    ["cake", "케이크"],
    ["call", "부르다"],
    ["camera", "사진기"],
    ["camp", "야영지"],
  ],
    "Day11": [
    ["can", "할수있다"],
    ["candle", "양초"],
    ["candy", "사탕"],
    ["cap", "모자"],
    ["capital", "수도/대문자"],
    ["captain", "우두머리"],
    ["car", "자동차"],
    ["card", "카드"],
    ["care", "걱정/돌보다"],
    ["carry", "나르다"],
  ],
  "Day12": [
    ["case", "경우"],
    ["cassette", "카셋트"],
    ["cat", "고양이"],
    ["catch", "붙잡다"],
    ["ceiling", "천장"],
    ["center", "중앙"],
    ["chair", "의자"],
    ["chalk", "분필"],
    ["chance", "기회"],
    ["change", "바꾸다"],
  ],
  "Day13": [
    ["cheap", "값싼"],
    ["cheese", "치즈"],
    ["chicken", "닭"],
    ["child", "어린이"],
    ["chopstick", "젓가락"],
    ["church", "교회"],
    ["circle", "원"],
    ["city", "도시"],
    ["class", "학급"],
    ["classmate", "동급생"],
  ],
  "Day14": [
    ["clean", "깨끗한"],
    ["climb", "오르다"],
    ["clock", "시계"],
    ["close", "닫다"],
    ["clothes", "옷"],
    ["cloud", "구름"],
    ["club", "클럽"],
    ["coat", "코트"],
    ["coffee", "커피"],
    ["coin", "동전"],
  ],
  "Day15": [
    ["cold", "추운"],
    ["color", "색깔"],
    ["come", "오다"],
    ["computer", "컴퓨터"],
    ["cook", "요리하다"],
    ["cool", "시원한"],
    ["copy", "사본, 베끼다"],
    ["corner", "모퉁이"],
    ["count", "세다"],
    ["country", "지역"],
  ],
  "Day16": [
    ["course", "과정"],
    ["cousin", "사촌"],
    ["cover", "덮다"],
    ["cow", "암소"],
    ["crayon", "크레용"],
    ["cream", "크림"],
    ["cross", "가로지르다"],
    ["cry", "울다"],
    ["cup", "컵"],
    ["curtain", "커튼"],
  ],
  "Day17": [
    ["cut", "자르다"],
    ["dad", "아빠"],
    ["dance", "춤추다"],
    ["danger", "위험한"],
    ["dark", "어두운"],
    ["date", "날짜"],
    ["daughter", "딸"],
    ["day", "낮, 하루"],
    ["dead", "죽은"],
    ["deep", "깊은"],
  ],
  "Day18": [
    ["dear", "존경하는"],
    ["desk", "책상"],
    ["dial", "다이얼"],
    ["diary", "일기"],
    ["dictionary", "사전"],
    ["die", "죽다"],
    ["dinner", "저녁"],
    ["dirty", "더러운"],
    ["dish", "큰접시"],
    ["do", "하다"],
  ],
  "Day19": [
    ["doctor", "의사"],
    ["dog", "개"],
    ["doll", "인형"],
    ["dollar", "달러"],
    ["dolphin", "돌고래"],
    ["door", "문"],
    ["down", "아래에"],
    ["draw", "그리다"],
    ["dream", "꿈"],
    ["dress", "드레스"],
  ],
  "Day20": [
    ["drink", "마시다"],
    ["drive", "운전하다"],
    ["drop", "떨어지다, 방울"],
    ["drum", "북"],
    ["dry", "마른"],
    ["duck", "오리"],
    ["ear", "귀"],
    ["early", "일찍"],
    ["earth", "지구"],
    ["east", "동쪽"],
  ],
   "Day21": [
    ["easy", "쉬운"],
    ["eat", "먹다"],
    ["egg", "계란"],
    ["empty", "텅빈"],
    ["end", "끝"],
    ["engine", "엔진"],
    ["enjoy", "즐기다"],
    ["enough", "충분한"],
    ["eraser", "지우개"],
    ["evening", "저녁"],
  ],
  "Day22": [
    ["every", "모든, 모두의"],
    ["example", "예, 보기"],
    ["excellent", "뛰어난"],
    ["excite", "흥분시키다"],
    ["excuse", "용서하다"],
    ["exercise", "연습"],
    ["eye", "눈"],
    ["face", "얼굴"],
    ["fact", "사실"],
    ["fair", "공정한"],
  ],
  "Day23": [
    ["fall", "가을, 떨어지다"],
    ["family", "가족"],
    ["far", "멀리 떨어진"],
    ["farm", "농장"],
    ["fast", "빠른"],
    ["fat", "살찐"],
    ["famous", "유명한"],
    ["father", "아버지"],
    ["feel", "느끼다"],
    ["few", "다소 양이 적은"],
  ],
  "Day24": [
    ["field", "들판, 경기장"],
    ["fight", "싸움"],
    ["fill", "채우다"],
    ["film", "필름"],
    ["find", "찾다"],
    ["fine", "좋은, 맑은"],
    ["finger", "손가락"],
    ["finish", "끝내다"],
    ["fire", "불"],
    ["fish", "고기, 낚시하다"],
  ],
  "Day25": [
    ["fix", "고정시키다"],
    ["flag", "깃발"],
    ["floor", "마루"],
    ["flower", "꽃"],
    ["fly", "날다"],
    ["follow", "뒤를 따르다"],
    ["food", "음식"],
    ["fool", "바보"],
    ["foot", "발"],
    ["for", "~을 위하여, ~동안"],
  ],
  "Day26": [
    ["forget", "잊다"],
    ["fork", "포크"],
    ["free", "자유로운"],
    ["fresh", "신선한"],
    ["friend", "친구"],
    ["from", "~로부터"],
    ["front", "앞/정면"],
    ["fruit", "과일"],
    ["full", "가득찬"],
    ["fun", "즐거움"],
  ],
  "Day27": [
    ["game", "놀이"],
    ["garden", "정원"],
    ["gas", "가스, 휘발유"],
    ["gate", "문"],
    ["gentle", "온화한"],
    ["get", "얻다"],
    ["girl", "소녀"],
    ["give", "주다"],
    ["glad", "기쁜"],
    ["glass", "유리, 컵"],
  ],
  "Day28": [
    ["glove", "장갑"],
    ["go", "가다"],
    ["god(GOD)", "신, 하나님"],
    ["gold", "금"],
    ["good", "좋은"],
    ["grandmother", "할머니"],
    ["grape", "포도"],
    ["grass", "풀, 잔디"],
    ["gray", "회색"],
    ["great", "큰"],
  ],
  "Day29": [
    ["green", "녹색"],
    ["ground", "땅, 기초"],
    ["group", "단체"],
    ["grow", "성장하다"],
    ["guitar", "기타"],
    ["hair", "머리카락"],
    ["half", "절반"],
    ["hall", "회관, 넓은 방"],
    ["hamburger", "햄버거"],
    ["hand", "손"],
  ],
  "Day30": [
    ["handle", "손잡이"],
    ["happen", "발생하다"],
    ["happy", "행복한"],
    ["hard", "단단한, 열심히"],
    ["hat", "모자"],
    ["hate", "미워하다"],
    ["have", "가지고 있다"],
    ["he", "그, 남자"],
    ["head", "머리"],
    ["hear", "듣다"],
  ],
    "Day31": [
  ["heart", "마음"],
  ["heavy", "무거운"],
  ["hello", "여보세요"],
  ["help", "돕다"],
  ["hen", "암닭"],
  ["here", "여기에서"],
  ["hi", "안녕하세요"],
  ["hide", "숨기다"],
  ["high", "높은"],
  ["hiking", "하이킹, 도보여행"]
],

"Day32": [
  ["hill", "언덕"],
  ["hit", "때리다"],
  ["hold", "잡다"],
  ["hole", "구멍"],
  ["holiday", "휴일"],
  ["home", "집"],
  ["hope", "희망"],
  ["hose", "호스"],
  ["horse", "말"],
  ["hospital", "병원"]
],

"Day33": [
  ["hot", "뜨거운"],
  ["hotel", "호텔"],
  ["hour", "시간"],
  ["house", "집"],
  ["how", "어떻게"],
  ["hundred", "100"],
  ["hungry", "배고픈"],
  ["hurry", "서두르다"],
  ["hurt", "다치게하다"],
  ["I", "나"]
],

"Day34": [
  ["ice", "얼음"],
  ["idea", "생각"],
  ["if", "만약"],
  ["ill", "병든"],
  ["in", "~속"],
  ["ink", "잉크"],
  ["interest", "흥미"],
  ["into", "~속으로"],
  ["introduce", "소개하다"],
  ["island", "섬"]
],

"Day35": [
  ["it", "그것"],
  ["job", "직업"],
  ["join", "가입하다"],
  ["juice", "주스"],
  ["jump", "뛰어오르다"],
  ["jungle", "밀림지대"],
  ["just", "오직, 겨우"],
  ["keep", "지키다, 유지하다"],
  ["key", "열쇠"],
  ["kick", "차다"]
],

"Day36": [
  ["kid", "아이"],
  ["kill", "죽이다"],
  ["kind", "친절한, 종류"],
  ["king", "왕"],
  ["kitchen", "부엌"],
  ["knee", "무릎"],
  ["knife", "칼"],
  ["knock", "두드리다"],
  ["know", "알다"],
  ["lady", "숙녀"]
],

"Day37": [
  ["lake", "호수"],
  ["lamp", "등불"],
  ["land", "땅"],
  ["large", "큰, 넓은"],
  ["last", "마지막, 최근"],
  ["late", "늦은"],
  ["laugh", "웃다"],
  ["lead", "인도하다"],
  ["leaf", "잎"],
  ["learn", "배우다"]
],

"Day38": [
  ["leave", "떠나다"],
  ["left", "왼쪽"],
  ["leg", "다리"],
  ["lesson", "학과"],
  ["let", "허락하다"],
  ["letter", "편지"],
  ["library", "도서관"],
  ["lie", "눕다, 거짓말하다"],
  ["light", "빛"],
  ["like", "좋아하다"]
],

"Day39": [
  ["line", "선, 줄"],
  ["lion", "사자"],
  ["lip", "입술"],
  ["list", "목록"],
  ["listen", "듣다"],
  ["little", "작은"],
  ["live", "살다, 생생한"],
  ["long", "긴"],
  ["look", "바라보다"],
  ["lose", "잃다"]
],

"Day40": [
  ["lot", "많음"],
  ["loud", "소리가 큰"],
  ["love", "사랑하다"],
  ["low", "낮은"],
  ["luck", "행운"],
  ["lunch", "점심식사"],
  ["ma'am", "아주머니"],
  ["mad", "미친"],
  ["mail", "우편"],
  ["make", "만들다"]
],
}
