const wordLists = {
    "Day1": [
        ["resume", "이력서"],
        ["opening", "공석"],
        ["applicant", "지원자"],
        ["requirement", "필요조건"],
        ["meet", "만족시키다"],
        ["qualified", "자격있는"],
        ["candidate", "후보자"],
        ["confidence", "확신"],
        ["highly", "매우"],
        ["professional", "전문적인"],
        ["interview", "면접"],
        ["hire", "고용하다"],
        ["training", "교육"],
        ["reference", "추천서"],
        ["position", "일자리"],
        ["achievement", "성취"],
        ["impressed", "인상 깊게 생각하는"],
        ["excellent", "훌륭한"],
        ["eligible", "자격이 있는"],
        ["identify", "알아보다"],
        ["associate", "관련시키다"],
        ["condition", "조건"],
        ["employment", "고용"],
        ["lack", "~이 없다"],
        ["managerial", "관리의"],
        ["diligent", "성실한"],
        ["familiar", "익숙한"],
        ["proficiency", "숙달"],
        ["prospective", "장래의"],
        ["appeal", "관심을 끌다"],
        ["specialize", "~을 전공하다"],
        ["apprehensive", "걱정하는"],
        ["consultant", "고문"],
        ["entitle", "자격을 주다"],
        ["degree", "학위"],
        ["payroll", "임금대장"],
        ["recruit", "모집하다"],
        ["certification", "증명서"],
        ["occupation", "직업"],
        ["wage", "급료"],
    ],
    "Day2": [
        ["one", "하나"],
        ["two", "둘"],
        ["three", "셋"],
        ["four", "넷"],
        ["five", "다섯"],
        ["six", "여섯"],
        ["seven", "일곱"],
        ["eight", "여덟"],
        ["nine", "아홉"],
        ["ten", "열"],
        ["eleven", "열하나"],
        ["twelve", "열둘"],
        ["thirteen", "열셋"],
        ["fourteen", "열넷"],
        ["fifteen", "열다섯"]
    ]
}